### ISSUE TITLE
SyntaxError Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by pauldb09** [helperdiscord/centra#36]
![image](https://user-images.githubusercontent.com/70904183/159304351-2d2b6523-2f5e-49a4-85df-1542d217f35a.png)
## Environment

Node v16

**Comment by tbnritzdoge** [comment]
It appears that you are attempting to parse JSON from a response that isn't JSON so this isn't a library issue.

**Comment by sinkaroid** [comment]
In my case basically the JSON was valid, but it's messy on some version of node. Broke on 16.17.0 but not in 16.16.0 when using petitio

**Comment by dzlandis** [comment]
> In my case basically the JSON was valid, but it's messy on some version of node. Broke on 16.17.0 but not in 16.16.0 when using petitio

Experienced this same issue when trying to use petitio in Node version v16.18 when the JSON was valid. Was fixed by downgrading to v16.16.0 as the comment above mentions. Please fix and reopen this issue!

**Comment by DJCoolDev** [comment]
I can confirm this. A downgrade as mentioned above fixed the problem for me. However, it would be nice if it would also work in newer versions.
